-- FUNCTION TO GENERATE RANDOM DATE

-- CREATE THE SCHEME FUNCTION
-- TWO PARAMETER FOR THE START AND END THE YEAR THAT YOU WANT
CREATE OR REPLACE FUNCTION FCT_DATE_RANDOM 
(P_START_Y IN NUMBER,
P_END_Y IN NUMBER) RETURN CHAR -- RETURN CHAR BECAUSE RETURN DATE IS (DD/MM/YYYY HH:MM:SS)
IS

-- A VAR FOR EACH VALUE
V_DAY NUMBER(2);
V_MONTH NUMBER(2);
V_YEAR NUMBER(4);

-- A VAR FOR THE FULL DATE
V_DATE_FULL CHAR(10);

BEGIN
-- SELECT STRUCTURE FOR THE RANDONS NUMBERS
SELECT DBMS_RANDOM.value(P_START_Y,P_END_Y)NUM
INTO V_YEAR
FROM DUAL;

SELECT DBMS_RANDOM.value(01,30)NUM
INTO V_DAY
FROM DUAL;

SELECT DBMS_RANDOM.value(01,12)NUM
INTO V_MONTH
FROM DUAL;

-- PROCESS TO CONCATENATE DATE
V_DATE_FULL := V_DAY||'/'||V_MONTH||'/'||V_YEAR;

 RETURN (V_DATE_FULL);
END;

-- EXECUTE TEST
SELECT FCT_DATE_RANDOM(1997,1998),fct_date_random(1997,1998) FROM DUAL;