-- LABORATÓRIO DE UTL FILE

-- TABELA PARA LABORATÓRIO
CREATE TABLE TB_DEPTO_UTL AS 
SELECT * 
FROM DEPARTMENTS
WHERE ROWNUM=0;

-- PROCEDURE PARA GERAR UM ARQUIVO TXT COM
-- TODO O CONTEUDO DA TABELA DEPARTMENTS
CREATE OR REPLACE PROCEDURE PCR_READ_DEPTO_UTL IS

V_LINHA VARCHAR2(100);
V_ARQUIVO UTL_FILE.FILE_TYPE;

BEGIN

V_ARQUIVO := utl_file.fopen('DIR_UTL', 'DEPTO.TXT','W');

 FOR i IN (SELECT * FROM DEPARTMENTS) LOOP
 -- USAR UM DELIMITADOR PARA FACILITAR ARECUPERAÇÃO DOS DADOS
 V_LINHA := i.department_id||','||i.department_name||','
 ||i.location_id||','||i.manager_id;
 
 utl_file.put_line(V_ARQUIVO, V_LINHA);

 END LOOP;

utl_file.fclose(V_ARQUIVO);

END;

-- EXECUTAR A PROCEDURE
EXECUTE pcr_read_depto_utl;

-- CRIAR UMA PROCEDURE PARA INSERIR OS DADOS NA TABELA TB_DEPTO_UTL
CREATE OR REPLACE PROCEDURE PCR_WRITE_DEPTO_UTL IS

ARQUIVO_LER               UTL_FILE.FILE_TYPE;
LINHA                     VARCHAR2(100);

BEGIN
ARQUIVO_LER := utl_file.fopen('DIR_UTL', 'DEPTO.TXT','R');

    LOOP
        utl_file.get_line(ARQUIVO_LER, LINHA);
        INSERT INTO TB_DEPTO_UTL 
        -- USAR O REGEX_SUBSTR PARA DEFINIR A 
        -- POSIÇÃO DOS DADOS NO INSERT
        VALUES (REGEXP_SUBSTR(LINHA,'[^,]+', 1, 1),
                REGEXP_SUBSTR(LINHA,'[^,]+', 1, 2),
                REGEXP_SUBSTR(LINHA,'[^,]+', 1, 3),
                REGEXP_SUBSTR(LINHA,'[^,]+', 1, 4));
    END LOOP;
    
EXCEPTION WHEN NO_DATA_FOUND THEN
    UTL_FILE.FCLOSE(ARQUIVO_LER);

END;   

-- EXECUTAR A PROCEDURE E INSERIR OD DADOS
EXECUTE PCR_WRITE_DEPTO_UTL;

-- CONFERIR DADOS NA TABELA
SELECT * FROM TB_DEPTO_UTL;