-- CRIAR UMA TABELA CLONE, APENAS PARA AS INFORMAÇÕES
-- AUDITADAS PELA TRIGGER DE AUDITORIA
CREATE TABLE TB_DEPT_AUDIT AS(
SELECT * FROM DEPARTMENTS
WHERE ROWNUM=0);

ALTER TABLE TB_DEPT_AUDIT ADD
USUÁRIO VARCHAR2(50);

ALTER TABLE TB_DEPT_AUDIT ADD
TIPO_MANIP VARCHAR2(50);

ALTER TABLE TB_DEPT_AUDIT ADD
DATA_MANIP DATE;

-- TRIGGERS
CREATE OR REPLACE TRIGGER TRG_AUDIT_DEPT
BEFORE INSERT OR UPDATE OR DELETE ON DEPARTMENTS
FOR EACH ROW

DECLARE

BEGIN 
IF INSERTING THEN
  INSERT INTO TB_DEPT_AUDIT
  VALUES (:NEW.DEPARTMENT_ID,:NEW.DEPARTMENT_NAME,
          :NEW.MANAGER_ID,:NEW.LOCATION_ID,USER,
          'INSERT',SYSDATE);
ELSIF UPDATING THEN 
  INSERT INTO TB_DEPT_AUDIT
  VALUES (:NEW.DEPARTMENT_ID,:NEW.DEPARTMENT_NAME,
          :NEW.MANAGER_ID,:NEW.LOCATION_ID,USER,
          'UPDATE_NEW',SYSDATE);
  INSERT INTO TB_DEPT_AUDIT
  VALUES (:OLD.DEPARTMENT_ID,:OLD.DEPARTMENT_NAME,
          :OLD.MANAGER_ID,:OLD.LOCATION_ID,USER,
          'UPDATE_OLD',SYSDATE);
        
ELSIF DELETING THEN
  INSERT INTO TB_DEPT_AUDIT
  VALUES (:OLD.DEPARTMENT_ID,:OLD.DEPARTMENT_NAME,
          :OLD.MANAGER_ID,:OLD.LOCATION_ID,USER,
          'DELETE',SYSDATE);
END IF;
END;