-- PROGRAMANDO EM PL SQL
-- BLOCO PL/SQL

DECLARE 
-- OPCIONAL, PORÉM, SEMPRE TEM QU SER DECLARADA A VARIÁVEL
-- NO INÍCIO DO PROGRAMA, OBRIGATORIAMENTE USANDO O DECLARE
-- SEMPRE INICIAR VARIÁVEL COM V_

BEGIN 
-- OBRIGATÓRIO PARA EXECUÇÃO
-- DQL - SELECT 
-- DML - INSERT - UPDATE - DELETE
-- DDL - CREATE - ALTER - DROP - RENAME
    -- PSRS USAR COMANDOS DDL, UTILIZAR O COMANDO
    EXECUTE IMMEDIATE 

EXCEPTION 
-- OPCIONAL

END; 
-- OBRIGATÓRIO PARA FINALIZAR CADA PROGRAMA
