-- BOA RÁTICA PARA GANHO DE PERFORMANCE
-- USAR UMA ÚNICA VARIÁVEL PARA TODAS AS PESQUISAS
DECLARE
V_EMP EMPLOYEES%ROWTYPE;
BEGIN

SELECT FIRST_NAME, LAST_NAME
INTO V_EMP.FIRST_NAME, V_EMP.LAST_NAME
FROM employees
WHERE employee_id=100;

DBMS_OUTPUT.put_line(V_EMP.FIRST_NAME||' - ' ||
                     V_EMP.LAST_NAME);
-- EXCEPTION
END;