-- EXCEPTION

DECLARE
V_NAME EMPLOYEES.LAST_NAME%TYPE;


BEGIN
INSERT INTO DEPARTMENTS (DEPARTMENT_ID,
DEPARTMENT_NAME)
VALUES (10, 'TESTE');


EXCEPTION WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE(SQLCODE || ' - ' ||SQLERRM);
WHEN TOO_MANY_ROWS THEN 
DBMS_OUTPUT.PUT_LINE(SQLCODE || ' - ' ||SQLERRM);
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE(SQLCODE || ' - ' ||SQLERRM);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE(SQLCODE || ' - ' ||SQLERRM);

END;