SELECT SYSDATE FROM DUAL;

-- USAR INMEMORY PARA MELHORAR PERFOMACE, MANTER NA MEMÓRIA
-- E NÃO SÓ NO DISCO
CREATE TABLE TB_PRODUTOS (
    COD NUMBER,
    NOME VARCHAR2(50))
INMEMORY;

INSERT INTO TB_PRODUTOS VALUES (1,'TESTE');

SELECT * FROM TB_PRODUTOS;

-- INMEMORY COLUMN STORE
CREATE TABLE IM_COL_TAB (
    id   NUMBER,
    col1 NUMBER,
    col2 NUMBER,
    col3 NUMBER,
    col4 NUMBER
) INMEMORY
INMEMORY MEMCOMPRESS FOR QUERY HIGH(col1,col2)
INMEMORY MEMCOMPRESS FOR CAPACITY HIGH (col3)
NO INMEMORY (id, col4)
;

