-- PARA DECLAREAR MUITAS VARIÁVEIS
-- COLOCAR TODAS ABAIXO DO DECLARE 
DECLARE
V_FIRST VARCHAR2(50);
V_LAST VARCHAR2(50);
BEGIN

SELECT FIRST_NAME, LAST_NAME
INTO V_FIRST, V_LAST
FROM employees
WHERE employee_id=100;

DBMS_OUTPUT.put_line(v_first ||' - ' ||
                     v_last);
-- EXCEPTION
END;