CREATE OR REPLACE PROCEDURE PRC_UP_SAL (
P_DEPTO IN employees_two.department_name%TYPE,
P_FATOR IN NUMBER)
IS
   -- 10% DIREOTIRA
   -- 20% FINANCEIRO
   -- 30% VENDAS
   -- 5%  CONTABILIDADE
   -- 15% ESTOQUE   
V_AUMENTO NUMBER;

BEGIN

  IF P_DEPTO = 'DIRETORIA' THEN
    V_AUMENTO:=10;
  ELSIF P_DEPTO = 'FINANCEIRO' THEN
    V_AUMENTO:=20;
  ELSIF P_DEPTO = 'CONTABILIDADE' THEN
    V_AUMENTO:=15;
  END IF;
  
UPDATE employees_two
SET SALARY = (SALARY+SALARY*V_AUMENTO/P_FATOR)
WHERE department_name = P_DEPTO;

COMMIT;

END;