-- PROCEDURES 

CREATE OR REPLACE PROCEDURE PRC_CONS_DEPTO
(P_ID IN DEPARTMENTS.DEPARTMENT_ID%TYPE,
P_RESULT OUT DEPARTMENTS.DEPARTMENT_NAME%TYPE)

IS
BEGIN
 SELECT DEPARTMENT_NAME
 INTO P_RESULT
 FROM DEPARTMENTS
 WHERE DEPARTMENT_ID = P_ID;
END;


