-- SEUQENCE PARA AUTO INCREMENTO DE ALGUMA
-- COLUNA NA TABELA, DE FORMA SEQUENCIAL E 
-- NÃO REPETITIVA
CREATE SEQUENCE SEQ_DEPT_TRG
START WITH 1
INCREMENT BY 1;

--TRIGGER USANDO A SEQUENCE
CREATE OR REPLACE TRIGGER TRG_DEPT_SEQ
BEFORE INSERT ON TB_DEPT_TRG
FOR EACH ROW

DECLARE 
V_SEQ NUMBER;

BEGIN 

SELECT SEQ_DEPT_TRG.nextval
INTO V_SEQ
FROM DUAL;

:NEW.DEPARTMENT_ID:= V_SEQ;

END;

-- OBS: COMO ALTERAR COLUNA PARA SER PRIMARY KEY
ALTER TABLE TB_DEPT_TRG ADD CONSTRAINT 
PK_DEPARTMENT_NAME PRIMARY KEY (DEPARTMENT_ID);